### ISSUE TITLE
1.21 Server Crash: Attempted to load client-side class on dedicated server

### ISSUE THREAD

**Issue by ddalseong** [BrownBear85/swordinthestone#7]
## Description
When attempting to start a dedicated server with the "Sword In The Stone" mod installed, the server crashes due to an attempt to load a client-side class in a server-only environment.

## Environment
- Minecraft Version: 1.21
- NeoForge Version: 21.0.80-beta
- Mod Version: 2.0
- Server Type: Dedicated Server

## Error Log
```
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/model/ModelResourceLocation for invalid dist DEDICATED_SERVER
    at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.15.jar%2360!/:4.0] {}
    at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
    at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
    ...
    at TRANSFORMER/swordinthestone@2.0/com.bonker.swordinthestone.common.ability.SwordAbilities.register(SwordAbilities.java:421) ~[swordinthestone-2.0-1.21.jar%23267!/:?] {re:classloading}
    at TRANSFORMER/swordinthestone@2.0/com.bonker.swordinthestone.common.ability.SwordAbilities.<clinit>(SwordAbilities.java:64) ~[swordinthestone-2.0-1.21.jar%23267!/:?] {re:classloading}
    at TRANSFORMER/swordinthestone@2.0/com.bonker.swordinthestone.SwordInTheStone.<init>(SwordInTheStone.java:38) ~[swordinthestone-2.0-1.21.jar%23267!/:?] {re:classloading}
```

## Steps to Reproduce
1. Set up a dedicated Minecraft server with NeoForge 21.0.80-beta for Minecraft 1.21
2. Install the "Sword In The Stone" mod version 2.0
3. Attempt to start the server

## Expected Behavior
The server should start successfully with the mod loaded.

## Actual Behavior
The server crashes during startup, reporting an attempt to load a client-side class (`ModelResourceLocation`) in a server-only environment.

## Possible Solution
The mod needs to properly separate client-side and server-side code. The `ModelResourceLocation` class should only be referenced in client-side code or should be wrapped in a conditional check to ensure it's only accessed in a client environment.

## Additional Context
This issue appears to be related to improper side-only annotations or checks within the mod. Specifically, the problem occurs in the `SwordAbilities` class during registration (line 421) and initialization (line 64).

Please review the server-side compatibility of the mod, ensuring that client-only classes are not accessed in a dedicated server environment.

**Comment by BrownBear85** [comment]
Thanks for the detailed review! This is now fixed in the latest 1.21 release, and I apologize for my mistake.
